FROM node:18

WORKDIR /tasklist

COPY backend/package*.json ./backend/
WORKDIR /tasklist/backend
RUN npm install

WORKDIR /tasklist
COPY frontend ./frontend/
COPY backend ./backend/

CMD ["node", "backend/index.js"]